source 'https://rubygems.org'

gem 'rails', '4.2.2'

gem 'mysql2'

gem 'puma'

gem 'bitters'
gem 'bourbon'
gem 'cancancan'
gem 'capybara'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'coffee-rails'
gem 'delayed_job_active_record'
gem 'devise'
gem 'devise-async'
gem 'devise-async-activejob'
gem 'high_voltage'
gem 'jbuilder'
gem 'jquery-rails'
gem 'lograge'
gem 'neat'
gem 'normalize-rails'
gem 'ok_health_check'
gem 'poltergeist'
gem 'pry-rails'
gem 'pry-remote'
gem 'rails_12factor'
gem 'refills'
gem 'rspec-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'slim-rails'
gem 'spring'
gem 'turbolinks'
gem 'uglifier'
gem 'web-console'

